# Generated by Django 2.2.7 on 2019-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='age', max_length=16),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plan'), ('Above Ground', 'Above Ground')], help_text='location', max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], help_text='primary fur color', max_length=30),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='shift',
            field=models.CharField(choices=[('Am', 'AM'), ('Pm', 'PM')], help_text='shift', max_length=16),
        ),
    ]
