# Generated by Django 2.2.7 on 2019-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='latitude')),
                ('longitude', models.FloatField(help_text='longitude')),
                ('unique_squirrel_id', models.CharField(help_text='unique_squirrel_id', max_length=32)),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], help_text='shift', max_length=16)),
                ('date', models.DateField(help_text='date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='age', max_length=16)),
                ('primary_fur_color', models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('cinnamon', 'Cinnamon')], help_text='primary fur color', max_length=30)),
                ('location', models.CharField(choices=[('ground plane', 'Ground Plan'), ('above ground', 'Above Ground')], help_text='location', max_length=100)),
                ('specific_location', models.CharField(help_text='specific_location', max_length=100)),
                ('running', models.BooleanField(help_text='running')),
                ('chasing', models.BooleanField(help_text='chasing')),
                ('climbing', models.BooleanField(help_text='climbing')),
                ('eating', models.BooleanField(help_text='eating')),
                ('foraging', models.BooleanField(help_text='foraging')),
                ('other_activities', models.CharField(help_text='other_activities', max_length=100)),
                ('kuks', models.BooleanField(help_text='kuks')),
                ('quaas', models.BooleanField(help_text='quaas')),
                ('moans', models.BooleanField(help_text='moans')),
                ('tail_flags', models.BooleanField(help_text='tail_flags')),
                ('tail_twitches', models.BooleanField(help_text='tail_twitches')),
                ('approaches', models.BooleanField(help_text='approaches')),
                ('indifferent', models.BooleanField(help_text='indifferent')),
                ('runs_from', models.BooleanField(help_text='runs from')),
            ],
        ),
    ]
